### ISSUE TITLE
Replacing text in grouped object

### ISSUE THREAD

**Issue by Minchendai** [PaleNeutron/pptx-replace#1]
Hi John,

I'm currently using your pptx_replace package in my project. During my practice, I found out that the replace_text method in your package doesn't replace the text in a grouped shape. I've worked it out by myself, here's my solution:
![image](https://github.com/user-attachments/assets/86cba516-8c95-4f35-80b2-579a2b6e1b52)
Could you add this new feature to your package in the future?

Cheers, 
Minchen Dai

**Comment by PaleNeutron** [comment]
I create a commit for this feature, can you install this package from source to test if it works as designed?

**Comment by Minchendai** [comment]
Yes, it works now! Thanks！
